<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="IN-BAV-L0832" failures="1" tests="8" name="Default test" time="100.194" errors="0" timestamp="2021-04-05T15:12:31 IST">
  <testcase classname="com.tests.addresslinks.DestroyLinkTests" name="destroyLink" time="8.094"/>
  <testcase classname="com.tests.addresslinks.DestroyLinkTests" name="destroyLink" time="6.508"/>
  <testcase classname="com.tests.addresslinks.DestroyLinkTests" name="destroyLink" time="6.442"/>
  <testcase classname="com.tests.addresslinks.DestroyLinkTests" name="destroyLink" time="6.428"/>
  <testcase classname="com.tests.addresslinks.DestroyLinkTests" name="destroyLink" time="6.312"/>
  <testcase classname="com.tests.addresslinks.DestroyLinkTests" name="destroyLink" time="6.5"/>
  <testcase classname="com.tests.addresslinks.DestroyLinkTests" name="destroyLink" time="6.007"/>
  <testcase classname="com.tests.addresslinks.DestroyLinkTests" name="destroyLink" time="1.101">
    <failure type="java.lang.AssertionError" message="expected [http://a.testaddressbook.com/] but found [http://a.testaddressbook.com/session]">
      <![CDATA[java.lang.AssertionError: expected [http://a.testaddressbook.com/] but found [http://a.testaddressbook.com/session]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.tests.addresslinks.DestroyLinkTests.destroyLink(DestroyLinkTests.java:25)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- destroyLink -->
</testsuite> <!-- Default test -->
